### PR TITLE
Scm autoversion

### PR DESCRIPTION
**Pull request by mbkumar**
Auto-versioning by setuptools_scm package.
After a tag is created, for all subsequent commits, setuptools_scm will generate a new version that is dependent on the version specified in the last tag, the number of new commits, and the commit hash. Works for both wheels and sdist.

Addresses #117 and #91

### CODE REVIEW

**Comment by mbkumar** [comment]
Added mayavi to the docker build as well. And added optional dependencies for pyevtk, and mayavi and its dependencies. Fixed some bugs in the docker workflow.

**Comment by mbkumar** [comment]
@florianwechsung @landreman 
This PR is ready for merging.

**Comment by florianwechsung** [comment]
Not really an expert on this, but looks sensible. Can you summarise the changes to required/optional packages for visualisation too? just for our own records.

**Review by florianwechsung — DISMISSED** [review]

**Comment by mbkumar** [comment]
> Not really an expert on this, but looks sensible. Can you summarise the changes to required/optional packages for visualisation too? just for our own records.

Sure. 

For visualization, matplotlib is now a mandatory dependency. So it is always available. We can remove the checks for matplotlib. 

vtk, pyevtk, pyqt5, and mayavi are optional dependencies which could be installed along with simsopt by running the command `pip install simsopt[VIS]`

**Comment by mbkumar** [comment]
Updated the docker container image to include pyevtk.

**Review by landreman — APPROVED** [review]

**Pull request merged**
