### PR TITLE
WIP: aspect ratio and cross section

### PR DESCRIPTION
**Pull request by andrewgiuliani**
This pull request introduces:

1. computation of aspect ratio of surfaces using the VMEC definition of aspect ratio.  This is done in the `Surface.aspect_ratio`.
2. the capability of computing cross sections of surfaces at a given cylindrical angle.  This is done using bisection in the `Surface.cross_section`.
3. an implementation of `SurfaceXYZFourier.to_RZFourier` using `Surface.cross_section`.  This is done by computing cross sections of the `SurfaceXYZFourier` object and then fitting a `SurfaceRZFourier` to those cross sections.

For all of the above, unit tests are provided.

### CODE REVIEW

**Review by mbkumar — APPROVED** [review]
Thanks guys! The code looks much better.

**Comment by florianwechsung** [comment]
Can we undo this merge? I haven't reviewed the changes.

**Comment by mbkumar** [comment]
@florianwechsung, Sorry about that. This PR can't be reverted since I merged the other PR and made further commits to the master branch after merging this PR. You and Andrew could still keep working on it with Andrew opening a new pull request. Sorry about that.

@andrewgiuliani, could you please open a new pull request if Florian has any issues with this PR?

**Comment by florianwechsung** [comment]
Okay no worries, we'll make changes in a separate PR.

**Comment by mbkumar** [comment]
Thanks!

**Comment by andrewgiuliani** [comment]
Yes, I'll open a new PR to address any changes

**Pull request merged**
