### PR TITLE
Update to documentation. Added minimize_qfm.

### PR DESCRIPTION
**Pull request by ejpaul**
Update to documentation building for qfmsurface and added minimize_qfm method in response to Bharat's comment.

### CODE REVIEW

**Review by mbkumar — DISMISSED** [review]

**Comment by mbkumar** [comment]
@ejpaul 
The tests for Qfm seem fragile. Could you please investigate https://github.com/hiddenSymmetries/simsopt/pull/108/checks?check_run_id=3068412672

**Review by mbkumar — APPROVED** [review]

**Comment by mbkumar** [comment]
@ejpaul 

Thanks for the fixes.

**Comment by mbkumar** [comment]
@ejpaul 
Please let me know if I can delete the qfm_surf branch.

**Comment by ejpaul** [comment]
@mbkumar Yes you can delete it.

**Comment by mbkumar** [comment]
@ejpaul Thanks

**Pull request merged**
