### PR TITLE
Change license from LGPL to MIT

### PR DESCRIPTION
**Pull request by landreman**
Presently simsopt has the LGPL license. In the new world of private stellarator companies, this license is proving to be a complication. I’m most familiar with the perspective from Type One Energy, for which I do some consulting and where @mbkumar now works. Although scientists at the company are adding features to a private fork of simsopt, lawyers are advising them not to push these improvements to the public simsopt repo because the LGPL license could require open-sourcing of other proprietary code. The company is unsure about continuing to use simsopt generally due to this risk of the LGPL license affecting their IP. It would be better for everyone if the companies felt free to push improvements to the public repository so all users can benefit.

So, I propose we change the license to the MIT license. More information about the differences can be found [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository), [here](https://choosealicense.com/), and other sites. To change the license, my understanding is that we should get approval from everyone who has contributed code under the previous license: @mbkumar @florianwechsung @ejpaul @akaptano @rogeriojorge @abaillod @MigMadeira @mishapadidar @tmqian @kchammond @zhucaoxiang @phuslage @migueljmp @smiet @AlexWiedman @jons-pf @rahulgaur104 @andrewgiuliani @TacitusQ @jloizu @StanczakDominik @zhisong kindly approve the pull request or reply below to let us know if you approve of the change. If you have any concerns, let me know.

### CODE REVIEW

**Review by akaptano — DISMISSED** [review]

**Review by florianwechsung — APPROVED** [review]

**Review by andrewgiuliani — APPROVED** [review]

**Review by mbkumar — DISMISSED** [review]

**Review by rahulgaur104 — DISMISSED** [review]

**Review by rogeriojorge — APPROVED** [review]

**Review by jons-pf — APPROVED** [review]

**Review by StanczakDominik — APPROVED** [review]

**Review by zhucaoxiang — DISMISSED** [review]

**Review by ejpaul — APPROVED** [review]

**Review by abaillod — DISMISSED** [review]

**Comment by kchammond** [comment]
This is fine with me.

**Comment by migueljmp** [comment]
I approve

**Comment by MigMadeira** [comment]
I approve the change

**Comment by jloizu** [comment]
Hi again,


Since we at EPFL are very minor contributors, we do not want to oppose or stop the process for tool long, but I do have a question: it seems the Apache license is essentially as open as the MIT but ensures a reference to the origin of the code, which may be good, and about what has been changed, if I understood correctly. Why not Apache license instead of MIT?


Thanks,

Joaquim

________________________________

**Comment by jons-pf** [comment]
FYI, I use the Apache license for most of my OSS projects, but I agree that the MIT license can be described as even "less annoying". Let's stick with MIT for SIMSOPT.

**Review by zhisong — APPROVED** [review]

**Review by jloizu — DISMISSED** [review]
I approve the change of license.

**Review by smiet — DISMISSED** [review]

**Comment by smiet** [comment]
We're good at EPFL as well! Thanks for the patience!

**Review by tmqian — APPROVED** [review]
Sounds good to me! Thanks for the helpful links.

**Review by mbkumar — APPROVED** [review]

**Review by AlexWiedman — APPROVED** [review]

**Review by phuslage — APPROVED** [review]

**Comment by mishapadidar** [comment]
this is okay with me

**Comment by landreman** [comment]
Everyone who contributed code has now approved the change. Thank you to all of you for responding.

**Pull request merged**
