### PR TITLE
edits to cross section and the VMEC aspect ratio computation

### PR DESCRIPTION
**Pull request by andrewgiuliani**
Let's discuss here any required edits to the cross section and the VMEC aspect ratio computation

### CODE REVIEW

**Comment by florianwechsung** [comment]
@andrewgiuliani can you please check if you're happy with my edits? If yes, then we can merge this one.

**Comment by landreman** [comment]
Before merging, can you make sure the documentation builds (locally) without lots of warnings? Presently there are a bunch of warnings related to geo:
~~~
WARNING: autodoc: failed to import module 'objectives' from module 'simsopt.geo'; the following exception was raised:
No module named 'simsopt.geo.objectives'
/Users/mattland/simsopt/simsopt/src/simsopt/geo/surface.py:docstring of simsopt.geo.surface.Surface.aspect_ratio:8: WARNING: Unexpected indentation.
/Users/mattland/simsopt/simsopt/src/simsopt/geo/surface.py:docstring of simsopt.geo.surface.Surface.aspect_ratio:9: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/mattland/simsopt/simsopt/src/simsopt/geo/surface.py:docstring of simsopt.geo.surface.Surface.aspect_ratio:16: WARNING: Unexpected indentation.
/Users/mattland/simsopt/simsopt/src/simsopt/geo/surface.py:docstring of simsopt.geo.surface.Surface.aspect_ratio:19: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/mattland/simsopt/simsopt/src/simsopt/geo/surface.py:docstring of simsopt.geo.surface.Surface.aspect_ratio:23: WARNING: Unexpected indentation.
/Users/mattland/simsopt/simsopt/src/simsopt/geo/surface.py:docstring of simsopt.geo.surface.Surface.aspect_ratio:25: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/mattland/simsopt/simsopt/src/simsopt/geo/surface.py:docstring of simsopt.geo.surface.Surface.aspect_ratio:27: WARNING: Unexpected indentation.
/Users/mattland/simsopt/simsopt/src/simsopt/geo/surface.py:docstring of simsopt.geo.surface.Surface.aspect_ratio:28: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/mattland/simsopt/simsopt/src/simsopt/geo/surface.py:docstring of simsopt.geo.surface.Surface.aspect_ratio:34: WARNING: Unexpected indentation.
/Users/mattland/simsopt/simsopt/src/simsopt/geo/surface.py:docstring of simsopt.geo.surface.Surface.aspect_ratio:35: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/mattland/simsopt/simsopt/src/simsopt/geo/surfacexyzfourier.py:docstring of simsopt.geo.surfacexyzfourier.SurfaceXYZFourier:6: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/mattland/simsopt/simsopt/src/simsopt/geo/surfacexyzfourier.py:docstring of simsopt.geo.surfacexyzfourier.SurfaceXYZFourier:7: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/mattland/simsopt/simsopt/src/simsopt/geo/surfacexyzfourier.py:docstring of simsopt.geo.surfacexyzfourier.SurfaceXYZFourier:11: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/mattland/simsopt/simsopt/src/simsopt/geo/surfacexyzfourier.py:docstring of simsopt.geo.surfacexyzfourier.SurfaceXYZFourier:12: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/mattland/simsopt/simsopt/src/simsopt/geo/surfacexyzfourier.py:docstring of simsopt.geo.surfacexyzfourier.SurfaceXYZFourier:20: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/mattland/simsopt/simsopt/src/simsopt/geo/surface.py:docstring of simsopt.geo.surface.Surface.aspect_ratio:9: WARNING: Unknown target name: "s".
~~~~
See https://github.com/hiddenSymmetries/simsopt/blob/master/docs/README.md - you may need to run `sphinx-apidoc`

**Comment by andrewgiuliani** [comment]
Thanks for these comments, on it

**Review by florianwechsung — APPROVED** [review]

**Review by florianwechsung — APPROVED** [review]

**Comment by florianwechsung** [comment]
Can you merge in master and resolve the conflicts? I assume much of it is just formatting. Could try running autopep on this branch first and then merging, that might reduce the number of conflictts.

**Pull request merged**
