### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by mbkumar**
This PR addresses the trouble in installing MHD code dependencies for simsopt (Issue #35). An efficient docker container based on ubuntu is built for simsopt. All the dependencies including the optional ones such as VMEC and SPEC are installed along with simsopt in the container. The docker container includes

1. a python virtual environment containing simsopt and all of its python dependencies such as VMEC and booz_xform along with standard python packages.
2. SPEC executable at /usr/bin
3. Editors such as vim, nano and emacs for editing files
4. IPython kernel and jupyter notebook framework
5. bash as default command

The changes include:
1. updates to documentation on installing and running the simsopt container
2. Dockerfile containing multi-stage build steps for simsopt docker image.

Things to do:
1. Come up with another image or extend this image for development purposes as well.

### CODE REVIEW

**Comment by landreman** [comment]
At least on my macbook, vmec is much slower when run from the container than when run directly. After pulling the latest container, I ran the following script several times on my mac both inside and outside the container, using 1 MPI process:
~~~
from time import time
from simsopt.mhd.vmec import Vmec

t1 = time()
v = Vmec('input.LandremanSenguptaPlunk_section5p3_low_res')
v.run()
t2 = time()
print('Elapsed time:', t2 - t1)
~~~
The input file is available at https://github.com/hiddenSymmetries/VMEC2000/tree/master/python/tests. Typical run time is 2 sec outside the container and 24 sec inside.

**Comment by mbkumar** [comment]
Could you please check if it is due to resource constraints?
https://docs.docker.com/config/containers/resource_constraints/

Bharat Medasani

Engineer
Princeton Plasma Physics Lab (PPPL)

**Comment by landreman** [comment]
For that VMEC script example, `top` shows it uses just 97 MB when run outside the container. So I would have thought docker's default 2 GB limit would be plenty. Nonetheless, raising the memory limit in Docker preferences to 10 GB, that VMEC script now takes about 2.6-3 sec. Maybe in the future we could improve the speed a bit more, but that's good enough for now. 

When running with >1 MPI processes, both for that previous example or other simsopt VMEC examples, there are a bunch of messages printed like
~~~
[5503c80a9555:00031] Read -1, expected 7280, errno = 1
[5503c80a9555:00030] Read -1, expected 6720, errno = 1
[5503c80a9555:00031] Read -1, expected 7280, errno = 1
[5503c80a9555:00030] Read -1, expected 6720, errno = 1
[5503c80a9555:00030] Read -1, expected 6720, errno = 1
[5503c80a9555:00031] Read -1, expected 7280, errno = 1
[5503c80a9555:00030] Read -1, expected 6720, errno = 1
[5503c80a9555:00031] Read -1, expected 7280, errno = 1
[5503c80a9555:00030] Read -1, expected 6912, errno = 1
[5503c80a9555:00031] Read -1, expected 7488, errno = 1
[5503c80a9555:00030] Read -1, expected 6912, errno = 1
[5503c80a9555:00031] Read -1, expected 7488, errno = 1
~~~
although it looks like the code runs correctly. Any idea what those messages are about?

**Comment by mbkumar** [comment]
@landreman, @florianwechsung 
Few updates:

1) Removed old style SPEC installation, which is not used anymore.
2) Coverage improvements that include MPI and MHD tests. Coverage now at 81%.
3) Boost added to the docker container.

IMO, this is ready to be merged.

**Review by landreman — APPROVED** [review]

**Comment by landreman** [comment]
Should `:test` be added to the end of the container name `hiddensymmetries/simsopt` in `docs/source/docker.rst`? Or will that tag be unnecessary soon?

**Comment by mbkumar** [comment]
The docker container built from docker branch is given the tag "test".
Once the PR is merged,  the tag generated is "latest", which is the default
tag. You don't need to specify the default tag. So test tag is not needed
once the PR is merged.

**Review by florianwechsung — APPROVED** [review]

**Review by florianwechsung — APPROVED** [review]

**Comment by florianwechsung** [comment]
Looks good to me. I added a section on how to create persistent containers to the documentation.

**Pull request merged**
