### PR TITLE
Mgrid improvements

### PR DESCRIPTION
**Pull request by aaroncbader**
This PR updates the mgrid writing script to also include the arrays for the Magnetic Potential.  These values are needed in some codes (such as BMW).

There is a separate issue in the mgrid to allow for calculation of multiple coil sets separately with scaled currents, but that requires some more thought.

### CODE REVIEW

**Comment by mbkumar** [comment]
In the MGrid class, the method `from_file` should read the A_vec data as well.

**Comment by landreman** [comment]
I've never seen mgrid files that contain the vector potential before. Is there some version of xgrid other than the one in stellopt that writes mgrid files containing A? mgrid files are already quite large and storing A makes them twice as big, and vmec doesn't need A, so I'm not sure it makes sense to always include A.

**Comment by aaroncbader** [comment]
> I've never seen mgrid files that contain the vector potential before. Is there some version of xgrid other than the one in stellopt that writes mgrid files containing A? mgrid files are already quite large and storing A makes them twice as big, and vmec doesn't need A, so I'm not sure it makes sense to always include A.

The oak ridge version of MakeGrid includes the vector potential.  It is necessary to run BMW.

**Comment by aaroncbader** [comment]
Will make including potential optional and default to off

**Comment by aaroncbader** [comment]
I would like to update the test that reads an mgrid file to include one with the potential fields enabled.  But I don't know how to regenerate the test mgrid file.

**Comment by landreman** [comment]
It looks like that test file `mgrid.pnas-qa-test-lowres-standard.nc` was added by Tony Qian, so you could ask him. Or just use a different file for testing mgrid files that contain A.

**Comment by aaroncbader** [comment]
Should I be worried about the failed tests?

**Comment by mbkumar** [comment]
@aaroncbader The issue is not with your tests, but one of Spec tests is failing. I am not sure if that test is using the mgrid file that was modified, but I doubt it.

**Comment by aaroncbader** [comment]
There looks to be an issue with loading mgrids. But it's not one that I introduced.  Simsopt is unable to load mgrids that it saves.  It looks like this problem predates my changes.  I'll see if I can fix it.

**Comment by landreman** [comment]
> Should I be worried about the failed tests?

No need to worry - these failures are a known problem, #357, which is independent of this PR. @abaillod @smiet Any hope of fixing #357?

**Comment by aaroncbader** [comment]
ok, I've fixed up the mgrid `from_file` function and added a test for a new mgrid with a potential value

**Review by landreman — APPROVED** [review]

**Pull request merged**
