### PR TITLE
Add more surface plot options

### PR DESCRIPTION
**Pull request by zhucaoxiang**
This is a quick fix to #134.

I have adopted multiple plot engines to plot the toroidal surface in 3D.

What I have changed:
   - add options for using `Matplotlib` and `Plotly`.
   - add `**kwargs` to pass advanced plotting arguments.
 
Something we can discuss:
  - I haven't prepared the options `plot_normal`, `plot_derivative` for the other two engines. It might be messy, especially when using `matplotlib`. 
  - I forgot which docstring format we are using. I looked at other parts and try to follow similar conventions. 
  - The default engine is `matplotlib`, which can be changed to `mayavi` for backward capabilities.

### CODE REVIEW

**Comment by zhucaoxiang** [comment]
I have updated the plotting functions for both curves and surfaces, but I have problems testing it on my MacBook #139 . By the way, I didn't found too many examples using `surface.go` (maybe I missed). For example, in this case, I would like to create a toroidal surface and plot it. I don't find an example showing how to do this.

For a demonstration of plotly, you can check this page. https://zhucaoxiang.github.io/CoilPy/examples/Plot_with_plotly.html

**Comment by florianwechsung** [comment]
I'm not sure what you are referring to with `surface.go`. Can you expand?

To create a toroidal surface in simsopt, simply 
```
from simsopt.geo.surfacerzfourier import SurfaceRZFourier
s = SurfaceRZFourier()
```
This defaults to a torus with major radius 1 and minor radius 0.1.

**Comment by zhucaoxiang** [comment]
@florianwechsung Sorry, I was saying `geo.Surface`. But what you provide should enough for a test (after I installed it on my MacBook).

**Comment by zhucaoxiang** [comment]
I think it is now working. Here is a simple example plotting both curves and surfaces using plotly (forgive me that I chose a curve lying inside the surface).
image

I have add some docstring in the source introducing the arguments. I am happy to add some documentation as long as someone can kindly direct me where I should put.

**Comment by landreman** [comment]
This looks excellent. Thanks @zhucaoxiang for working on this. I will try to add a basic unit test for plotting today.

**Review by landreman — APPROVED** [review]

**Pull request merged**
